/*
 * Copyright (C) 2024-2025 Hideki Ikeda
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.kotlingeekdev.urireference

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertTrue


class URIReferenceTest {
    @Test
    fun test_parse() {
        val uriRef1 = URIReference.parse("http://example.com")
        assertEquals("http://example.com", uriRef1.toString())
        assertEquals(false, uriRef1.isRelativeReference)
        assertEquals("http", uriRef1.scheme)
        assertEquals(true, uriRef1.hasAuthority())
        assertEquals("example.com", uriRef1.authority.toString())
        assertEquals(null, uriRef1.userinfo)
        assertEquals("example.com", uriRef1.host.toString())
        assertEquals("example.com", uriRef1.host!!.value)
        assertEquals(HostType.REGNAME, uriRef1.host!!.type)
        assertEquals(-1, uriRef1.port)
        assertEquals("", uriRef1.path)
        assertEquals(null, uriRef1.query)
        assertEquals(null, uriRef1.fragment)

        val uriRef2 = URIReference.parse("hTTp://example.com")
        assertEquals("hTTp://example.com", uriRef2.toString())
        assertEquals(false, uriRef2.isRelativeReference)
        assertEquals("hTTp", uriRef2.scheme)
        assertEquals(true, uriRef2.hasAuthority())
        assertEquals("example.com", uriRef2.authority.toString())
        assertEquals(null, uriRef2.userinfo)
        assertEquals("example.com", uriRef2.host.toString())
        assertEquals("example.com", uriRef2.host!!.value)
        assertEquals(HostType.REGNAME, uriRef2.host!!.type)
        assertEquals(-1, uriRef2.port)
        assertEquals("", uriRef2.path)
        assertEquals(null, uriRef2.query)
        assertEquals(null, uriRef2.fragment)

        val uriRef3 = URIReference.parse("//example.com")
        assertEquals("//example.com", uriRef3.toString())
        assertEquals(true, uriRef3.isRelativeReference)
        assertEquals(null, uriRef3.scheme)
        assertEquals(true, uriRef3.hasAuthority())
        assertEquals("example.com", uriRef3.authority.toString())
        assertEquals(null, uriRef3.userinfo)
        assertEquals("example.com", uriRef3.host.toString())
        assertEquals("example.com", uriRef3.host!!.value)
        assertEquals(HostType.REGNAME, uriRef3.host!!.type)
        assertEquals(-1, uriRef3.port)
        assertEquals("", uriRef3.path)
        assertEquals(null, uriRef3.query)
        assertEquals(null, uriRef3.fragment)

        val uriRef4 = URIReference.parse("http:")
        assertEquals(false, uriRef4.isRelativeReference)
        assertEquals("http", uriRef4.scheme)
        assertEquals(false, uriRef4.hasAuthority())
        assertEquals(null, uriRef4.authority)
        assertEquals(null, uriRef4.userinfo)
        assertEquals(null, uriRef4.host)
        assertEquals(-1, uriRef4.port)
        assertEquals("", uriRef4.path)
        assertEquals(null, uriRef4.query)
        assertEquals(null, uriRef4.fragment)

        val uriRef5 = URIReference.parse("http://john@example.com")
        assertEquals("http://john@example.com", uriRef5.toString())
        assertEquals(false, uriRef5.isRelativeReference)
        assertEquals("http", uriRef5.scheme)
        assertEquals(true, uriRef5.hasAuthority())
        assertEquals("john@example.com", uriRef5.authority.toString())
        assertEquals("john", uriRef5.userinfo)
        assertEquals("example.com", uriRef5.host.toString())
        assertEquals("example.com", uriRef5.host!!.value)
        assertEquals(HostType.REGNAME, uriRef5.host!!.type)
        assertEquals(-1, uriRef5.port)
        assertEquals("", uriRef5.path)
        assertEquals(null, uriRef5.query)
        assertEquals(null, uriRef5.fragment)

        val uriRef6 = URIReference.parse("http://%6A%6F%68%6E@example.com")
        assertEquals("http://%6A%6F%68%6E@example.com", uriRef6.toString())
        assertEquals(false, uriRef6.isRelativeReference)
        assertEquals("http", uriRef6.scheme)
        assertEquals(true, uriRef6.hasAuthority())
        assertEquals("%6A%6F%68%6E@example.com", uriRef6.authority.toString())
        assertEquals("%6A%6F%68%6E", uriRef6.userinfo)
        assertEquals("example.com", uriRef6.host.toString())
        assertEquals("example.com", uriRef6.host!!.value)
        assertEquals(HostType.REGNAME, uriRef6.host!!.type)
        assertEquals(-1, uriRef6.port)
        assertEquals("", uriRef6.path)
        assertEquals(null, uriRef6.query)
        assertEquals(null, uriRef6.fragment)

        val uriRef7 = URIReference.parse("http://101.102.103.104")
        assertEquals("http://101.102.103.104", uriRef7.toString())
        assertEquals(false, uriRef7.isRelativeReference)
        assertEquals("http", uriRef7.scheme)
        assertEquals(true, uriRef7.hasAuthority())
        assertEquals("101.102.103.104", uriRef7.authority.toString())
        assertEquals(null, uriRef7.userinfo)
        assertEquals("101.102.103.104", uriRef7.host.toString())
        assertEquals("101.102.103.104", uriRef7.host!!.value)
        assertEquals(HostType.IPV4, uriRef7.host!!.type)
        assertEquals(-1, uriRef7.port)
        assertEquals("", uriRef7.path)
        assertEquals(null, uriRef7.query)
        assertEquals(null, uriRef7.fragment)

        val uriRef8 = URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]")
        assertEquals("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]", uriRef8.toString())
        assertEquals(false, uriRef8.isRelativeReference)
        assertEquals("http", uriRef8.scheme)
        assertEquals(true, uriRef8.hasAuthority())
        assertEquals("[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]", uriRef8.authority.toString())
        assertEquals(null, uriRef8.authority!!.userinfo)
        assertEquals("[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]", uriRef8.host.toString())
        assertEquals("[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]", uriRef8.host!!.value)
        assertEquals(HostType.IPV6, uriRef8.host!!.type)
        assertEquals(-1, uriRef8.port)
        assertEquals("", uriRef8.path)
        assertEquals(null, uriRef8.query)
        assertEquals(null, uriRef8.fragment)

        val uriRef9 = URIReference.parse("http://[2001:db8:0:1:1:1:1:1]")
        assertEquals("http://[2001:db8:0:1:1:1:1:1]", uriRef9.toString())
        assertEquals(false, uriRef9.isRelativeReference)
        assertEquals("http", uriRef9.scheme)
        assertEquals(true, uriRef9.hasAuthority())
        assertEquals("[2001:db8:0:1:1:1:1:1]", uriRef9.authority.toString())
        assertEquals(null, uriRef9.userinfo)
        assertEquals("[2001:db8:0:1:1:1:1:1]", uriRef9.host.toString())
        assertEquals("[2001:db8:0:1:1:1:1:1]", uriRef9.host!!.value)
        assertEquals(HostType.IPV6, uriRef9.host!!.type)
        assertEquals(-1, uriRef9.port)
        assertEquals("", uriRef9.path)
        assertEquals(null, uriRef9.query)
        assertEquals(null, uriRef9.fragment)

        val uriRef10 = URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]")
        assertEquals("http://[2001:0:9d38:6abd:0:0:0:42]", uriRef10.toString())
        assertEquals(false, uriRef10.isRelativeReference)
        assertEquals("http", uriRef10.scheme)
        assertEquals(true, uriRef10.hasAuthority())
        assertEquals("[2001:0:9d38:6abd:0:0:0:42]", uriRef10.authority.toString())
        assertEquals(null, uriRef10.userinfo)
        assertEquals("[2001:0:9d38:6abd:0:0:0:42]", uriRef10.host.toString())
        assertEquals("[2001:0:9d38:6abd:0:0:0:42]", uriRef10.host!!.value)
        assertEquals(HostType.IPV6, uriRef10.host!!.type)
        assertEquals(-1, uriRef10.port)
        assertEquals("", uriRef10.path)
        assertEquals(null, uriRef10.query)
        assertEquals(null, uriRef10.fragment)

        val uriRef11 = URIReference.parse("http://[fe80::1]")
        assertEquals("http://[fe80::1]", uriRef11.toString())
        assertEquals(false, uriRef11.isRelativeReference)
        assertEquals("http", uriRef11.scheme)
        assertEquals(true, uriRef11.hasAuthority())
        assertEquals("[fe80::1]", uriRef11.authority.toString())
        assertEquals(null, uriRef11.userinfo)
        assertEquals("[fe80::1]", uriRef11.host.toString())
        assertEquals("[fe80::1]", uriRef11.host!!.value)
        assertEquals(HostType.IPV6, uriRef11.host!!.type)
        assertEquals(-1, uriRef11.port)
        assertEquals("", uriRef11.path)
        assertEquals(null, uriRef11.query)
        assertEquals(null, uriRef11.fragment)

        val uriRef12 = URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]")
        assertEquals("http://[2001:0:3238:DFE1:63::FEFB]", uriRef12.toString())
        assertEquals(false, uriRef12.isRelativeReference)
        assertEquals("http", uriRef12.scheme)
        assertEquals(true, uriRef12.hasAuthority())
        assertEquals("[2001:0:3238:DFE1:63::FEFB]", uriRef12.authority.toString())
        assertEquals(null, uriRef12.userinfo)
        assertEquals("[2001:0:3238:DFE1:63::FEFB]", uriRef12.host.toString())
        assertEquals("[2001:0:3238:DFE1:63::FEFB]", uriRef12.host!!.value)
        assertEquals(HostType.IPV6, uriRef12.host!!.type)
        assertEquals(-1, uriRef12.port)
        assertEquals("", uriRef12.path)
        assertEquals(null, uriRef12.query)
        assertEquals(null, uriRef12.fragment)

        val uriRef13 = URIReference.parse("http://[v1.fe80::a+en1]")
        assertEquals("http://[v1.fe80::a+en1]", uriRef13.toString())
        assertEquals(false, uriRef13.isRelativeReference)
        assertEquals("http", uriRef13.scheme)
        assertEquals(true, uriRef13.hasAuthority())
        assertEquals("[v1.fe80::a+en1]", uriRef13.authority.toString())
        assertEquals(null, uriRef13.userinfo)
        assertEquals("[v1.fe80::a+en1]", uriRef13.host.toString())
        assertEquals("[v1.fe80::a+en1]", uriRef13.host!!.value)
        assertEquals(HostType.IPVFUTURE, uriRef13.host!!.type)
        assertEquals(-1, uriRef13.port)
        assertEquals("", uriRef13.path)
        assertEquals(null, uriRef13.query)
        assertEquals(null, uriRef13.fragment)

        val uriRef14 = URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D")
        assertEquals("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D", uriRef14.toString())
        assertEquals(false, uriRef14.isRelativeReference)
        assertEquals("http", uriRef14.scheme)
        assertEquals(true, uriRef14.hasAuthority())
        assertEquals("%65%78%61%6D%70%6C%65%2E%63%6F%6D", uriRef14.authority.toString())
        assertEquals(null, uriRef14.userinfo)
        assertEquals("%65%78%61%6D%70%6C%65%2E%63%6F%6D", uriRef14.host.toString())
        assertEquals("%65%78%61%6D%70%6C%65%2E%63%6F%6D", uriRef14.host!!.value)
        assertEquals(HostType.REGNAME, uriRef14.host!!.type)
        assertEquals(-1, uriRef14.port)
        assertEquals("", uriRef14.path)
        assertEquals(null, uriRef14.query)
        assertEquals(null, uriRef14.fragment)

        val uriRef15 = URIReference.parse("http://")
        assertEquals(false, uriRef15.isRelativeReference)
        assertEquals("http", uriRef15.scheme)
        assertEquals(true, uriRef15.hasAuthority())
        assertEquals("", uriRef15.authority.toString())
        assertEquals(null, uriRef15.userinfo)
        assertEquals("", uriRef15.host.toString())
        assertEquals("", uriRef15.host!!.value)
        assertEquals(HostType.REGNAME, uriRef15.host!!.type)
        assertEquals(-1, uriRef15.port)
        assertEquals("", uriRef15.path)
        assertEquals(null, uriRef15.query)
        assertEquals(null, uriRef15.fragment)

        val uriRef16 = URIReference.parse("http:///a")
        assertEquals(false, uriRef16.isRelativeReference)
        assertEquals("http", uriRef16.scheme)
        assertEquals(true, uriRef16.hasAuthority())
        assertEquals("", uriRef16.authority.toString())
        assertEquals(null, uriRef16.userinfo)
        assertEquals("", uriRef16.host.toString())
        assertEquals("", uriRef16.host!!.value)
        assertEquals(HostType.REGNAME, uriRef16.host!!.type)
        assertEquals(-1, uriRef16.port)
        assertEquals("/a", uriRef16.path)
        assertEquals(null, uriRef16.query)
        assertEquals(null, uriRef16.fragment)

        val uriRef17 = URIReference.parse("http://example.com:80")
        assertEquals(false, uriRef17.isRelativeReference)
        assertEquals("http", uriRef17.scheme)
        assertEquals(true, uriRef17.hasAuthority())
        assertEquals("example.com:80", uriRef17.authority.toString())
        assertEquals(null, uriRef17.userinfo)
        assertEquals("example.com", uriRef17.host.toString())
        assertEquals("example.com", uriRef17.host!!.value)
        assertEquals(HostType.REGNAME, uriRef17.host!!.type)
        assertEquals(80, uriRef17.port)
        assertEquals("", uriRef17.path)
        assertEquals(null, uriRef17.query)
        assertEquals(null, uriRef17.fragment)

        val uriRef18 = URIReference.parse("http://example.com:")
        assertEquals(false, uriRef18.isRelativeReference)
        assertEquals("http", uriRef18.scheme)
        assertEquals(true, uriRef18.hasAuthority())
        assertEquals("example.com", uriRef18.authority.toString())
        assertEquals(null, uriRef18.userinfo)
        assertEquals("example.com", uriRef18.host.toString())
        assertEquals("example.com", uriRef18.host!!.value)
        assertEquals(HostType.REGNAME, uriRef18.host!!.type)
        assertEquals(-1, uriRef18.port)
        assertEquals("", uriRef18.path)
        assertEquals(null, uriRef18.query)
        assertEquals(null, uriRef18.fragment)

        val uriRef19 = URIReference.parse("http://example.com:001")
        assertEquals(false, uriRef19.isRelativeReference)
        assertEquals("http", uriRef19.scheme)
        assertEquals(true, uriRef19.hasAuthority())
        assertEquals("example.com:1", uriRef19.authority.toString())
        assertEquals(null, uriRef19.authority!!.userinfo)
        assertEquals("example.com", uriRef19.host.toString())
        assertEquals("example.com", uriRef19.host!!.value)
        assertEquals(HostType.REGNAME, uriRef19.host!!.type)
        assertEquals(1, uriRef19.port)
        assertEquals("", uriRef19.path)
        assertEquals(null, uriRef19.query)
        assertEquals(null, uriRef19.fragment)

        val uriRef20 = URIReference.parse("http://example.com/a/b/c")
        assertEquals("http://example.com/a/b/c", uriRef20.toString())
        assertEquals(false, uriRef20.isRelativeReference)
        assertEquals("http", uriRef20.scheme)
        assertEquals(true, uriRef20.hasAuthority())
        assertEquals("example.com", uriRef20.authority.toString())
        assertEquals(null, uriRef20.authority!!.userinfo)
        assertEquals("example.com", uriRef20.host.toString())
        assertEquals("example.com", uriRef20.host!!.value)
        assertEquals(HostType.REGNAME, uriRef20.host!!.type)
        assertEquals(-1, uriRef20.port)
        assertEquals("/a/b/c", uriRef20.path)
        assertEquals(null, uriRef20.query)
        assertEquals(null, uriRef20.fragment)

        val uriRef21 = URIReference.parse("http://example.com/%61/%62/%63")
        assertEquals("http://example.com/%61/%62/%63", uriRef21.toString())
        assertEquals(false, uriRef21.isRelativeReference)
        assertEquals("http", uriRef21.scheme)
        assertEquals(true, uriRef21.hasAuthority())
        assertEquals("example.com", uriRef21.authority.toString())
        assertEquals(null, uriRef21.userinfo)
        assertEquals("example.com", uriRef21.host.toString())
        assertEquals("example.com", uriRef21.host!!.value)
        assertEquals(HostType.REGNAME, uriRef21.host!!.type)
        assertEquals(-1, uriRef21.port)
        assertEquals("/%61/%62/%63", uriRef21.path)
        assertEquals(null, uriRef21.query)
        assertEquals(null, uriRef21.fragment)

        val uriRef22 = URIReference.parse("http:/a")
        assertEquals(false, uriRef22.isRelativeReference)
        assertEquals("http", uriRef22.scheme)
        assertEquals(false, uriRef22.hasAuthority())
        assertEquals(null, uriRef22.authority)
        assertEquals(null, uriRef22.userinfo)
        assertEquals(null, uriRef22.host)
        assertEquals(-1, uriRef22.port)
        assertEquals("/a", uriRef22.path)
        assertEquals(null, uriRef22.query)
        assertEquals(null, uriRef22.fragment)

        val uriRef23 = URIReference.parse("http:a")
        assertEquals(false, uriRef23.isRelativeReference)
        assertEquals("http", uriRef23.scheme)
        assertEquals(false, uriRef23.hasAuthority())
        assertEquals(null, uriRef23.authority)
        assertEquals(null, uriRef23.userinfo)
        assertEquals(null, uriRef23.host)
        assertEquals(-1, uriRef23.port)
        assertEquals("a", uriRef23.path)
        assertEquals(null, uriRef23.query)
        assertEquals(null, uriRef23.fragment)

        val uriRef24 = URIReference.parse("//")
        assertEquals(true, uriRef24.isRelativeReference)
        assertEquals(null, uriRef24.scheme)
        assertEquals(true, uriRef24.hasAuthority())
        assertEquals("", uriRef24.authority.toString())
        assertEquals(null, uriRef24.userinfo)
        assertEquals("", uriRef24.host.toString())
        assertEquals("", uriRef24.host!!.value)
        assertEquals(HostType.REGNAME, uriRef24.host!!.type)
        assertEquals(-1, uriRef24.port)
        assertEquals("", uriRef24.path)
        assertEquals(null, uriRef24.query)
        assertEquals(null, uriRef24.fragment)

        val uriRef25 = URIReference.parse("http://example.com?q")
        assertEquals(false, uriRef25.isRelativeReference)
        assertEquals("http", uriRef25.scheme)
        assertEquals(true, uriRef25.hasAuthority())
        assertEquals("example.com", uriRef25.authority.toString())
        assertEquals(null, uriRef25.userinfo)
        assertEquals("example.com", uriRef25.host.toString())
        assertEquals("example.com", uriRef25.host!!.value)
        assertEquals(HostType.REGNAME, uriRef25.host!!.type)
        assertEquals(-1, uriRef25.port)
        assertEquals("", uriRef25.path)
        assertEquals("q", uriRef25.query)
        assertEquals(null, uriRef25.fragment)

        val uriRef26 = URIReference.parse("http://example.com?")
        assertEquals(false, uriRef26.isRelativeReference)
        assertEquals("http", uriRef26.scheme)
        assertEquals(true, uriRef26.hasAuthority())
        assertEquals("example.com", uriRef26.authority.toString())
        assertEquals(null, uriRef26.userinfo)
        assertEquals("example.com", uriRef26.host.toString())
        assertEquals("example.com", uriRef26.host!!.value)
        assertEquals(HostType.REGNAME, uriRef26.host!!.type)
        assertEquals(-1, uriRef26.port)
        assertEquals("", uriRef26.path)
        assertEquals("", uriRef26.query)
        assertEquals(null, uriRef26.fragment)

        val uriRef27 = URIReference.parse("http://example.com#f")
        assertEquals(false, uriRef27.isRelativeReference)
        assertEquals("http", uriRef27.scheme)
        assertEquals(true, uriRef27.hasAuthority())
        assertEquals("example.com", uriRef27.authority.toString())
        assertEquals(null, uriRef27.userinfo)
        assertEquals("example.com", uriRef27.host.toString())
        assertEquals("example.com", uriRef27.host!!.value)
        assertEquals(HostType.REGNAME, uriRef27.host!!.type)
        assertEquals(-1, uriRef27.port)
        assertEquals("", uriRef27.path)
        assertEquals(null, uriRef27.query)
        assertEquals("f", uriRef27.fragment)

        val uriRef28 = URIReference.parse("http://example.com#")
        assertEquals(false, uriRef28.isRelativeReference)
        assertEquals("http", uriRef28.scheme)
        assertEquals(true, uriRef28.hasAuthority())
        assertEquals("example.com", uriRef28.authority.toString())
        assertEquals(null, uriRef28.userinfo)
        assertEquals("example.com", uriRef28.host.toString())
        assertEquals("example.com", uriRef28.host!!.value)
        assertEquals(HostType.REGNAME, uriRef28.host!!.type)
        assertEquals(-1, uriRef28.port)
        assertEquals("", uriRef28.path)
        assertEquals(null, uriRef28.query)
        assertEquals("", uriRef28.fragment)

        val uriRef29 = URIReference.parse("")
        assertEquals(true, uriRef29.isRelativeReference)
        assertEquals(null, uriRef29.scheme)
        assertEquals(false, uriRef29.hasAuthority())
        assertEquals(null, uriRef29.authority)
        assertEquals(null, uriRef29.userinfo)
        assertEquals(null, uriRef29.host)
        assertEquals(-1, uriRef29.port)
        assertEquals("", uriRef29.path)
        assertEquals(null, uriRef29.query)
        assertEquals(null, uriRef29.fragment)

        TestUtils.assertThrowsIAE<Throwable>(
            "The path value is invalid.",
            { URIReference.parse("1invalid://example.com") })

        TestUtils.assertThrowsIAE<Throwable>(
            "The host value \"v@w\" has an invalid character \"@\" at the index 1.",
            { URIReference.parse("http://u@v@w") })

        TestUtils.assertThrowsIAE<Throwable>(
            "The port value \"1:2:3\" has an invalid character \":\" at the index 1.",
            { URIReference.parse("http://example.com:1:2:3") })

        TestUtils.assertThrowsIAE<Throwable>(
            "The query value \"[invalid_query]\" has an invalid character \"[\" at the index 0.",
            { URIReference.parse("http://example.com?[invalid_query]") })

        TestUtils.assertThrowsIAE<Throwable>(
            "The fragment value \"[invalid_fragment]\" has an invalid character \"[\" at the index 0.",
            { URIReference.parse("http://example.com#[invalid_fragment]") })

        TestUtils.assertThrowsIAE<Throwable>(
            "The port value \"b\" has an invalid character \"b\" at the index 0.",
            { URIReference.parse("//a:b") })

        TestUtils.assertThrowsIAE<Throwable>(
            "The port value \":\" has an invalid character \":\" at the index 0.",
            { URIReference.parse("//::") })
    }


    @Test
    fun test_isRelativeReference() {
        assertEquals(false, URIReference.parse("http://example.com").isRelativeReference)
        assertEquals(false, URIReference.parse("hTTp://example.com").isRelativeReference)
        assertEquals(true, URIReference.parse("//example.com").isRelativeReference)
        assertEquals(false, URIReference.parse("http:").isRelativeReference)
        assertEquals(false, URIReference.parse("http://john@example.com").isRelativeReference)
        assertEquals(false, URIReference.parse("http://%6A%6F%68%6E@example.com").isRelativeReference)
        assertEquals(false, URIReference.parse("http://101.102.103.104").isRelativeReference)
        assertEquals(
            false,
            URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").isRelativeReference
        )
        assertEquals(false, URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").isRelativeReference)
        assertEquals(false, URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").isRelativeReference)
        assertEquals(false, URIReference.parse("http://[fe80::1]").isRelativeReference)
        assertEquals(false, URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").isRelativeReference)
        assertEquals(false, URIReference.parse("http://[v1.fe80::a+en1]").isRelativeReference)
        assertEquals(
            false,
            URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").isRelativeReference
        )
        assertEquals(false, URIReference.parse("http://").isRelativeReference)
        assertEquals(false, URIReference.parse("http:///a").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com:80").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com:").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com:001").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com/a/b/c").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com/%61/%62/%63").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com?q").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com?").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com#f").isRelativeReference)
        assertEquals(false, URIReference.parse("http://example.com#").isRelativeReference)
        assertEquals(false, URIReference.parse("http:/a").isRelativeReference)
        assertEquals(false, URIReference.parse("http:a").isRelativeReference)
        assertEquals(true, URIReference.parse("//").isRelativeReference)
        assertEquals(true, URIReference.parse("").isRelativeReference)
    }


    @Test
    fun test_getScheme() {
        assertEquals("http", URIReference.parse("http://example.com").scheme)
        assertEquals("hTTp", URIReference.parse("hTTp://example.com").scheme)
        assertEquals(null, URIReference.parse("//example.com").scheme)
        assertEquals("http", URIReference.parse("http:").scheme)
        assertEquals("http", URIReference.parse("http://john@example.com").scheme)
        assertEquals("http", URIReference.parse("http://%6A%6F%68%6E@example.com").scheme)
        assertEquals("http", URIReference.parse("http://101.102.103.104").scheme)
        assertEquals("http", URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").scheme)
        assertEquals("http", URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").scheme)
        assertEquals("http", URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").scheme)
        assertEquals("http", URIReference.parse("http://[fe80::1]").scheme)
        assertEquals("http", URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").scheme)
        assertEquals("http", URIReference.parse("http://[v1.fe80::a+en1]").scheme)
        assertEquals("http", URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").scheme)
        assertEquals("http", URIReference.parse("http://").scheme)
        assertEquals("http", URIReference.parse("http:///a").scheme)
        assertEquals("http", URIReference.parse("http://example.com:80").scheme)
        assertEquals("http", URIReference.parse("http://example.com:").scheme)
        assertEquals("http", URIReference.parse("http://example.com:001").scheme)
        assertEquals("http", URIReference.parse("http://example.com/a/b/c").scheme)
        assertEquals("http", URIReference.parse("http://example.com/%61/%62/%63").scheme)
        assertEquals("http", URIReference.parse("http://example.com?q").scheme)
        assertEquals("http", URIReference.parse("http://example.com?").scheme)
        assertEquals("http", URIReference.parse("http://example.com#f").scheme)
        assertEquals("http", URIReference.parse("http://example.com#").scheme)
        assertEquals("http", URIReference.parse("http:/a").scheme)
        assertEquals("http", URIReference.parse("http:a").scheme)
        assertEquals(null, URIReference.parse("//").scheme)
        assertEquals(null, URIReference.parse("").scheme)
    }


    @Test
    fun test_hasAuthority() {
        assertEquals(true, URIReference.parse("http://example.com").hasAuthority())
        assertEquals(true, URIReference.parse("hTTp://example.com").hasAuthority())
        assertEquals(true, URIReference.parse("//example.com").hasAuthority())
        assertEquals(false, URIReference.parse("http:").hasAuthority())
        assertEquals(true, URIReference.parse("http://john@example.com").hasAuthority())
        assertEquals(true, URIReference.parse("http://%6A%6F%68%6E@example.com").hasAuthority())
        assertEquals(true, URIReference.parse("http://101.102.103.104").hasAuthority())
        assertEquals(
            true,
            URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").hasAuthority()
        )
        assertEquals(true, URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").hasAuthority())
        assertEquals(true, URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").hasAuthority())
        assertEquals(true, URIReference.parse("http://[fe80::1]").hasAuthority())
        assertEquals(true, URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").hasAuthority())
        assertEquals(true, URIReference.parse("http://[v1.fe80::a+en1]").hasAuthority())
        assertEquals(true, URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").hasAuthority())
        assertEquals(true, URIReference.parse("http://").hasAuthority())
        assertEquals(true, URIReference.parse("http:///a").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com:80").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com:").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com:001").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com/a/b/c").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com/%61/%62/%63").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com?q").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com?").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com#f").hasAuthority())
        assertEquals(true, URIReference.parse("http://example.com#").hasAuthority())
        assertEquals(false, URIReference.parse("http:/a").hasAuthority())
        assertEquals(false, URIReference.parse("http:a").hasAuthority())
        assertEquals(true, URIReference.parse("//").hasAuthority())
        assertEquals(false, URIReference.parse("").hasAuthority())
    }


    @Test
    fun test_getAuthority() {
        assertEquals(Authority.parse("example.com"), URIReference.parse("http://example.com").authority)
        assertEquals(Authority.parse("example.com"), URIReference.parse("hTTp://example.com").authority)
        assertEquals(Authority.parse("example.com"), URIReference.parse("//example.com").authority)
        assertEquals(null, URIReference.parse("http:").authority)
        assertEquals(
            Authority.parse("john@example.com"),
            URIReference.parse("http://john@example.com").authority
        )
        assertEquals(
            Authority.parse("%6A%6F%68%6E@example.com"),
            URIReference.parse("http://%6A%6F%68%6E@example.com").authority
        )
        assertEquals(
            Authority.parse("101.102.103.104"),
            URIReference.parse("http://101.102.103.104").authority
        )
        assertEquals(
            Authority.parse("[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]"),
            URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").authority
        )
        assertEquals(
            Authority.parse("[2001:db8:0:1:1:1:1:1]"),
            URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").authority
        )
        assertEquals(
            Authority.parse("[2001:0:9d38:6abd:0:0:0:42]"),
            URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").authority
        )
        assertEquals(Authority.parse("[fe80::1]"), URIReference.parse("http://[fe80::1]").authority)
        assertEquals(
            Authority.parse("[2001:0:3238:DFE1:63::FEFB]"),
            URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").authority
        )
        assertEquals(
            Authority.parse("[v1.fe80::a+en1]"),
            URIReference.parse("http://[v1.fe80::a+en1]").authority
        )
        assertEquals(
            Authority.parse("%65%78%61%6D%70%6C%65%2E%63%6F%6D"),
            URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").authority
        )
        assertEquals(Authority.parse(""), URIReference.parse("http://").authority)
        assertEquals(Authority.parse(""), URIReference.parse("http:///a").authority)
        assertEquals(
            Authority.parse("example.com:80"),
            URIReference.parse("http://example.com:80").authority
        )
        assertEquals(Authority.parse("example.com"), URIReference.parse("http://example.com:").authority)
        assertEquals(
            Authority.parse("example.com:001"),
            URIReference.parse("http://example.com:001").authority
        )
        assertEquals(
            Authority.parse("example.com"),
            URIReference.parse("http://example.com/a/b/c").authority
        )
        assertEquals(
            Authority.parse("example.com"),
            URIReference.parse("http://example.com/%61/%62/%63").authority
        )
        assertEquals(Authority.parse("example.com"), URIReference.parse("http://example.com?q").authority)
        assertEquals(Authority.parse("example.com"), URIReference.parse("http://example.com?").authority)
        assertEquals(Authority.parse("example.com"), URIReference.parse("http://example.com#f").authority)
        assertEquals(Authority.parse("example.com"), URIReference.parse("http://example.com#").authority)
        assertEquals(null, URIReference.parse("http:/a").authority)
        assertEquals(null, URIReference.parse("http:a").authority)
        assertEquals(Authority.parse(""), URIReference.parse("//").authority)
        assertEquals(null, URIReference.parse("").authority)
    }


    @Test
    fun test_getUserInfo() {
        assertEquals(null, URIReference.parse("http://example.com").userinfo)
        assertEquals(null, URIReference.parse("hTTp://example.com").userinfo)
        assertEquals(null, URIReference.parse("//example.com").userinfo)
        assertEquals(null, URIReference.parse("http:").userinfo)
        assertEquals("john", URIReference.parse("http://john@example.com").userinfo)
        assertEquals("%6A%6F%68%6E", URIReference.parse("http://%6A%6F%68%6E@example.com").userinfo)
        assertEquals(null, URIReference.parse("http://101.102.103.104").userinfo)
        assertEquals(null, URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").userinfo)
        assertEquals(null, URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").userinfo)
        assertEquals(null, URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").userinfo)
        assertEquals(null, URIReference.parse("http://[fe80::1]").userinfo)
        assertEquals(null, URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").userinfo)
        assertEquals(null, URIReference.parse("http://[v1.fe80::a+en1]").userinfo)
        assertEquals(null, URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").userinfo)
        assertEquals(null, URIReference.parse("http://").userinfo)
        assertEquals(null, URIReference.parse("http:///a").userinfo)
        assertEquals(null, URIReference.parse("http://example.com:80").userinfo)
        assertEquals(null, URIReference.parse("http://example.com:").userinfo)
        assertEquals(null, URIReference.parse("http://example.com:001").userinfo)
        assertEquals(null, URIReference.parse("http://example.com/a/b/c").userinfo)
        assertEquals(null, URIReference.parse("http://example.com/%61/%62/%63").userinfo)
        assertEquals(null, URIReference.parse("http://example.com?q").userinfo)
        assertEquals(null, URIReference.parse("http://example.com?").userinfo)
        assertEquals(null, URIReference.parse("http://example.com#f").userinfo)
        assertEquals(null, URIReference.parse("http://example.com#").userinfo)
        assertEquals(null, URIReference.parse("http:/a").userinfo)
        assertEquals(null, URIReference.parse("http:a").userinfo)
        assertEquals(null, URIReference.parse("//").userinfo)
        assertEquals(null, URIReference.parse("").userinfo)
    }


    @Test
    fun testHost() {
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("hTTp://example.com").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("//example.com").host)
        assertEquals(null, URIReference.parse("http:").host)
        assertEquals(
            Host(HostType.REGNAME, "example.com"),
            URIReference.parse("http://john@example.com").host
        )
        assertEquals(
            Host(HostType.REGNAME, "example.com"),
            URIReference.parse("http://%6A%6F%68%6E@example.com").host
        )
        assertEquals(
            Host(HostType.IPV4, "101.102.103.104"),
            URIReference.parse("http://101.102.103.104").host
        )
        assertEquals(
            Host(HostType.IPV6, "[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]"),
            URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").host
        )
        assertEquals(
            Host(HostType.IPV6, "[2001:db8:0:1:1:1:1:1]"),
            URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").host
        )
        assertEquals(
            Host(HostType.IPV6, "[2001:0:9d38:6abd:0:0:0:42]"),
            URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").host
        )
        assertEquals(Host(HostType.IPV6, "[fe80::1]"), URIReference.parse("http://[fe80::1]").host)
        assertEquals(
            Host(HostType.IPV6, "[2001:0:3238:DFE1:63::FEFB]"),
            URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").host
        )
        assertEquals(
            Host(HostType.IPVFUTURE, "[v1.fe80::a+en1]"),
            URIReference.parse("http://[v1.fe80::a+en1]").host
        )
        assertEquals(
            Host(HostType.REGNAME, "%65%78%61%6D%70%6C%65%2E%63%6F%6D"),
            URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").host
        )
        assertEquals(Host(HostType.REGNAME, ""), URIReference.parse("http://").host)
        assertEquals(Host(HostType.REGNAME, ""), URIReference.parse("http:///a").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com:80").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com:").host)
        assertEquals(
            Host(HostType.REGNAME, "example.com"),
            URIReference.parse("http://example.com:001").host
        )
        assertEquals(
            Host(HostType.REGNAME, "example.com"),
            URIReference.parse("http://example.com/a/b/c").host
        )
        assertEquals(
            Host(HostType.REGNAME, "example.com"),
            URIReference.parse("http://example.com/%61/%62/%63").host
        )
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com?q").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com?").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com#f").host)
        assertEquals(Host(HostType.REGNAME, "example.com"), URIReference.parse("http://example.com#").host)
        assertEquals(null, URIReference.parse("http:/a").host)
        assertEquals(null, URIReference.parse("http:a").host)
        assertEquals(Host(HostType.REGNAME, ""), URIReference.parse("//").host)
        assertEquals(null, URIReference.parse("").host)
    }


    @Test
    fun test_getPort() {
        assertEquals(-1, URIReference.parse("http://example.com").port)
        assertEquals(-1, URIReference.parse("hTTp://example.com").port)
        assertEquals(-1, URIReference.parse("//example.com").port)
        assertEquals(-1, URIReference.parse("http:").port)
        assertEquals(-1, URIReference.parse("http://john@example.com").port)
        assertEquals(-1, URIReference.parse("http://%6A%6F%68%6E@example.com").port)
        assertEquals(-1, URIReference.parse("http://101.102.103.104").port)
        assertEquals(-1, URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").port)
        assertEquals(-1, URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").port)
        assertEquals(-1, URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").port)
        assertEquals(-1, URIReference.parse("http://[fe80::1]").port)
        assertEquals(-1, URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").port)
        assertEquals(-1, URIReference.parse("http://[v1.fe80::a+en1]").port)
        assertEquals(-1, URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").port)
        assertEquals(-1, URIReference.parse("http://").port)
        assertEquals(-1, URIReference.parse("http:///a").port)
        assertEquals(80, URIReference.parse("http://example.com:80").port)
        assertEquals(-1, URIReference.parse("http://example.com:").port)
        assertEquals(1, URIReference.parse("http://example.com:001").port)
        assertEquals(-1, URIReference.parse("http://example.com/a/b/c").port)
        assertEquals(-1, URIReference.parse("http://example.com/%61/%62/%63").port)
        assertEquals(-1, URIReference.parse("http://example.com?q").port)
        assertEquals(-1, URIReference.parse("http://example.com?").port)
        assertEquals(-1, URIReference.parse("http://example.com#f").port)
        assertEquals(-1, URIReference.parse("http://example.com#").port)
        assertEquals(-1, URIReference.parse("http:/a").port)
        assertEquals(-1, URIReference.parse("http:a").port)
        assertEquals(-1, URIReference.parse("//").port)
        assertEquals(-1, URIReference.parse("").port)
    }


    @Test
    fun test_getPath() {
        assertEquals("", URIReference.parse("http://example.com").path)
        assertEquals("", URIReference.parse("hTTp://example.com").path)
        assertEquals("", URIReference.parse("//example.com").path)
        assertEquals("", URIReference.parse("http:").path)
        assertEquals("", URIReference.parse("http://john@example.com").path)
        assertEquals("", URIReference.parse("http://%6A%6F%68%6E@example.com").path)
        assertEquals("", URIReference.parse("http://101.102.103.104").path)
        assertEquals("", URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").path)
        assertEquals("", URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").path)
        assertEquals("", URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").path)
        assertEquals("", URIReference.parse("http://[fe80::1]").path)
        assertEquals("", URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").path)
        assertEquals("", URIReference.parse("http://[v1.fe80::a+en1]").path)
        assertEquals("", URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").path)
        assertEquals("", URIReference.parse("http://").path)
        assertEquals("/a", URIReference.parse("http:///a").path)
        assertEquals("", URIReference.parse("http://example.com:80").path)
        assertEquals("", URIReference.parse("http://example.com:").path)
        assertEquals("", URIReference.parse("http://example.com:001").path)
        assertEquals("/a/b/c", URIReference.parse("http://example.com/a/b/c").path)
        assertEquals("/%61/%62/%63", URIReference.parse("http://example.com/%61/%62/%63").path)
        assertEquals("", URIReference.parse("http://example.com?q").path)
        assertEquals("", URIReference.parse("http://example.com?").path)
        assertEquals("", URIReference.parse("http://example.com#f").path)
        assertEquals("", URIReference.parse("http://example.com#").path)
        assertEquals("/a", URIReference.parse("http:/a").path)
        assertEquals("a", URIReference.parse("http:a").path)
        assertEquals("", URIReference.parse("//").path)
        assertEquals("", URIReference.parse("").path)
    }


    @Test
    fun test_getQuery() {
        assertEquals(null, URIReference.parse("http://example.com").query)
        assertEquals(null, URIReference.parse("hTTp://example.com").query)
        assertEquals(null, URIReference.parse("//example.com").query)
        assertEquals(null, URIReference.parse("http:").query)
        assertEquals(null, URIReference.parse("http://john@example.com").query)
        assertEquals(null, URIReference.parse("http://%6A%6F%68%6E@example.com").query)
        assertEquals(null, URIReference.parse("http://101.102.103.104").query)
        assertEquals(null, URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").query)
        assertEquals(null, URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").query)
        assertEquals(null, URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").query)
        assertEquals(null, URIReference.parse("http://[fe80::1]").query)
        assertEquals(null, URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").query)
        assertEquals(null, URIReference.parse("http://[v1.fe80::a+en1]").query)
        assertEquals(null, URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").query)
        assertEquals(null, URIReference.parse("http://").query)
        assertEquals(null, URIReference.parse("http:///a").query)
        assertEquals(null, URIReference.parse("http://example.com:80").query)
        assertEquals(null, URIReference.parse("http://example.com:").query)
        assertEquals(null, URIReference.parse("http://example.com:001").query)
        assertEquals(null, URIReference.parse("http://example.com/a/b/c").query)
        assertEquals(null, URIReference.parse("http://example.com/%61/%62/%63").query)
        assertEquals("q", URIReference.parse("http://example.com?q").query)
        assertEquals("", URIReference.parse("http://example.com?").query)
        assertEquals(null, URIReference.parse("http://example.com#f").query)
        assertEquals(null, URIReference.parse("http://example.com#").query)
        assertEquals(null, URIReference.parse("http:/a").query)
        assertEquals(null, URIReference.parse("http:a").query)
        assertEquals(null, URIReference.parse("//").query)
        assertEquals(null, URIReference.parse("").query)
    }


    @Test
    fun test_getFragment() {
        assertEquals(null, URIReference.parse("http://example.com").fragment)
        assertEquals(null, URIReference.parse("hTTp://example.com").fragment)
        assertEquals(null, URIReference.parse("//example.com").fragment)
        assertEquals(null, URIReference.parse("http:").fragment)
        assertEquals(null, URIReference.parse("http://john@example.com").fragment)
        assertEquals(null, URIReference.parse("http://%6A%6F%68%6E@example.com").fragment)
        assertEquals(null, URIReference.parse("http://101.102.103.104").fragment)
        assertEquals(null, URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]").fragment)
        assertEquals(null, URIReference.parse("http://[2001:db8:0:1:1:1:1:1]").fragment)
        assertEquals(null, URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]").fragment)
        assertEquals(null, URIReference.parse("http://[fe80::1]").fragment)
        assertEquals(null, URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]").fragment)
        assertEquals(null, URIReference.parse("http://[v1.fe80::a+en1]").fragment)
        assertEquals(null, URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D").fragment)
        assertEquals(null, URIReference.parse("http://").fragment)
        assertEquals(null, URIReference.parse("http:///a").fragment)
        assertEquals(null, URIReference.parse("http://example.com:80").fragment)
        assertEquals(null, URIReference.parse("http://example.com:").fragment)
        assertEquals(null, URIReference.parse("http://example.com:001").fragment)
        assertEquals(null, URIReference.parse("http://example.com/a/b/c").fragment)
        assertEquals(null, URIReference.parse("http://example.com/%61/%62/%63").fragment)
        assertEquals(null, URIReference.parse("http://example.com?q").fragment)
        assertEquals(null, URIReference.parse("http://example.com?").fragment)
        assertEquals("f", URIReference.parse("http://example.com#f").fragment)
        assertEquals("", URIReference.parse("http://example.com#").fragment)
        assertEquals(null, URIReference.parse("http:/a").fragment)
        assertEquals(null, URIReference.parse("http:a").fragment)
        assertEquals(null, URIReference.parse("//").fragment)
        assertEquals(null, URIReference.parse("").fragment)
    }


    @Test
    fun test_equals() {
        assertTrue(URIReference.parse("http://example.com") == URIReference.parse("http://example.com"))
        assertTrue(URIReference.parse("hTTp://example.com") == URIReference.parse("hTTp://example.com"))
        assertTrue(URIReference.parse("//example.com") == URIReference.parse("//example.com"))
        assertTrue(URIReference.parse("http:") == URIReference.parse("http:"))
        assertTrue(
            URIReference.parse("http://john@example.com") == URIReference.parse("http://john@example.com")
        )
        assertTrue(
            URIReference.parse("http://%6A%6F%68%6E@example.com") == URIReference.parse("http://%6A%6F%68%6E@example.com")
        )
        assertTrue(
            URIReference.parse("http://101.102.103.104") == URIReference.parse("http://101.102.103.104")
        )
        assertTrue(
            URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]") == URIReference.parse("http://[2001:0db8:0001:0000:0000:0ab9:C0A8:0102]")
        )
        assertTrue(
            URIReference.parse("http://[2001:db8:0:1:1:1:1:1]") == URIReference.parse("http://[2001:db8:0:1:1:1:1:1]")
        )
        assertTrue(
            URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]") == URIReference.parse("http://[2001:0:9d38:6abd:0:0:0:42]")
        )
        assertTrue(URIReference.parse("http://[fe80::1]") == URIReference.parse("http://[fe80::1]"))
        assertTrue(
            URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]") == URIReference.parse("http://[2001:0:3238:DFE1:63::FEFB]")
        )
        assertTrue(
            URIReference.parse("http://[v1.fe80::a+en1]") == URIReference.parse("http://[v1.fe80::a+en1]")
        )
        assertTrue(
            URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D") == URIReference.parse("http://%65%78%61%6D%70%6C%65%2E%63%6F%6D")
        )
        assertTrue(URIReference.parse("http://") == URIReference.parse("http://"))
        assertTrue(URIReference.parse("http:///a") == URIReference.parse("http:///a"))
        assertTrue(
            URIReference.parse("http://example.com:80") == URIReference.parse("http://example.com:80")
        )
        assertTrue(
            URIReference.parse("http://example.com:") == URIReference.parse("http://example.com:")
        )
        assertTrue(
            URIReference.parse("http://example.com:001") == URIReference.parse("http://example.com:001")
        )
        assertTrue(
            URIReference.parse("http://example.com/a/b/c") == URIReference.parse("http://example.com/a/b/c")
        )
        assertTrue(
            URIReference.parse("http://example.com/%61/%62/%63") == URIReference.parse("http://example.com/%61/%62/%63")
        )
        assertTrue(
            URIReference.parse("http://example.com?q") == URIReference.parse("http://example.com?q")
        )
        assertTrue(
            URIReference.parse("http://example.com?") == URIReference.parse("http://example.com?")
        )
        assertTrue(
            URIReference.parse("http://example.com#f") == URIReference.parse("http://example.com#f")
        )
        assertTrue(
            URIReference.parse("http://example.com#") == URIReference.parse("http://example.com#")
        )
        assertTrue(URIReference.parse("http:/a") == URIReference.parse("http:/a"))
        assertTrue(URIReference.parse("http:a") == URIReference.parse("http:a"))
        assertTrue(URIReference.parse("//") == URIReference.parse("//"))
        assertTrue(URIReference.parse("") == URIReference.parse(""))
        assertFalse(
            URIReference.parse("http://example.com/1ot") == URIReference.parse("http://example.com/1pU")
        )
    }


    @Test
    fun test_resolve() {
        val uriRef1 = URIReference.parse("http://a/b/c/d;p?q").resolve("g:h")
        assertEquals("g:h", uriRef1.toString())
        assertEquals(false, uriRef1!!.isRelativeReference)
        assertEquals("g", uriRef1.scheme)
        assertEquals(false, uriRef1.hasAuthority())
        assertEquals(null, uriRef1.authority)
        assertEquals(null, uriRef1.userinfo)
        assertEquals(null, uriRef1.host)
        assertEquals(-1, uriRef1.port)
        assertEquals("h", uriRef1.path)
        assertEquals(null, uriRef1.query)
        assertEquals(null, uriRef1.fragment)

        val uriRef2 = URIReference.parse("http://a/b/c/d;p?q").resolve("g")
        assertEquals("http://a/b/c/g", uriRef2.toString())
        assertEquals(false, uriRef2!!.isRelativeReference)
        assertEquals("http", uriRef2.scheme)
        assertEquals(true, uriRef2.hasAuthority())
        assertEquals("a", uriRef2.authority.toString())
        assertEquals(null, uriRef2.userinfo)
        assertEquals("a", uriRef2.host.toString())
        assertEquals("a", uriRef2.host!!.value)
        assertEquals(HostType.REGNAME, uriRef2.host!!.type)
        assertEquals(-1, uriRef2.port)
        assertEquals("/b/c/g", uriRef2.path)
        assertEquals(null, uriRef2.query)
        assertEquals(null, uriRef2.fragment)

        val uriRef3 = URIReference.parse("http://a/b/c/d;p?q").resolve("./g")
        assertEquals("http://a/b/c/g", uriRef3.toString())
        assertEquals(false, uriRef3!!.isRelativeReference)
        assertEquals("http", uriRef3.scheme)
        assertEquals(true, uriRef3.hasAuthority())
        assertEquals("a", uriRef3.authority.toString())
        assertEquals(null, uriRef3.userinfo)
        assertEquals("a", uriRef3.host.toString())
        assertEquals("a", uriRef3.host!!.value)
        assertEquals(HostType.REGNAME, uriRef3.host!!.type)
        assertEquals(-1, uriRef3.port)
        assertEquals("/b/c/g", uriRef3.path)
        assertEquals(null, uriRef3.query)
        assertEquals(null, uriRef3.fragment)

        val uriRef4 = URIReference.parse("http://a/b/c/d;p?q").resolve("g/")
        assertEquals("http://a/b/c/g/", uriRef4.toString())
        assertEquals(false, uriRef4!!.isRelativeReference)
        assertEquals("http", uriRef4.scheme)
        assertEquals(true, uriRef4.hasAuthority())
        assertEquals("a", uriRef4.authority.toString())
        assertEquals(null, uriRef4.userinfo)
        assertEquals("a", uriRef4.host.toString())
        assertEquals("a", uriRef4.host!!.value)
        assertEquals(HostType.REGNAME, uriRef4.host!!.type)
        assertEquals(-1, uriRef4.port)
        assertEquals("/b/c/g/", uriRef4.path)
        assertEquals(null, uriRef4.query)
        assertEquals(null, uriRef4.fragment)

        val uriRef5 = URIReference.parse("http://a/b/c/d;p?q").resolve("/g")
        assertEquals("http://a/g", uriRef5.toString())
        assertEquals(false, uriRef5!!.isRelativeReference)
        assertEquals("http", uriRef5.scheme)
        assertEquals(true, uriRef4.hasAuthority())
        assertEquals("a", uriRef4.authority.toString())
        assertEquals(null, uriRef4.userinfo)
        assertEquals("a", uriRef4.host.toString())
        assertEquals("a", uriRef4.host!!.value)
        assertEquals(HostType.REGNAME, uriRef4.host!!.type)
        assertEquals(-1, uriRef4.port)
        assertEquals("/g", uriRef5.path)
        assertEquals(null, uriRef5.query)
        assertEquals(null, uriRef5.fragment)

        val uriRef6 = URIReference.parse("http://a/b/c/d;p?q").resolve("//g")
        assertEquals("http://g", uriRef6.toString())
        assertEquals(false, uriRef6!!.isRelativeReference)
        assertEquals("http", uriRef6.scheme)
        assertEquals(true, uriRef6.hasAuthority())
        assertEquals("g", uriRef6.authority.toString())
        assertEquals(null, uriRef6.userinfo)
        assertEquals("g", uriRef6.host.toString())
        assertEquals("g", uriRef6.host!!.value)
        assertEquals(HostType.REGNAME, uriRef6.host!!.type)
        assertEquals(-1, uriRef6.port)
        assertEquals("", uriRef6.path)
        assertEquals(null, uriRef6.query)
        assertEquals(null, uriRef6.fragment)

        val uriRef7 = URIReference.parse("http://a/b/c/d;p?q").resolve("?y")
        assertEquals("http://a/b/c/d;p?y", uriRef7.toString())
        assertEquals(false, uriRef7!!.isRelativeReference)
        assertEquals("http", uriRef7.scheme)
        assertEquals(true, uriRef7.hasAuthority())
        assertEquals("a", uriRef7.authority.toString())
        assertEquals(null, uriRef7.userinfo)
        assertEquals("a", uriRef7.host.toString())
        assertEquals("a", uriRef7.host!!.value)
        assertEquals(HostType.REGNAME, uriRef7.host!!.type)
        assertEquals(-1, uriRef7.port)
        assertEquals("/b/c/d;p", uriRef7.path)
        assertEquals("y", uriRef7.query)
        assertEquals(null, uriRef7.fragment)

        val uriRef8 = URIReference.parse("http://a/b/c/d;p?q").resolve("g?y")
        assertEquals("http://a/b/c/g?y", uriRef8.toString())
        assertEquals(false, uriRef8!!.isRelativeReference)
        assertEquals("http", uriRef8.scheme)
        assertEquals(true, uriRef8.hasAuthority())
        assertEquals("a", uriRef8.authority.toString())
        assertEquals(null, uriRef8.userinfo)
        assertEquals("a", uriRef8.host.toString())
        assertEquals("a", uriRef8.host!!.value)
        assertEquals(HostType.REGNAME, uriRef8.host!!.type)
        assertEquals(-1, uriRef8.port)
        assertEquals("/b/c/g", uriRef8.path)
        assertEquals("y", uriRef8.query)
        assertEquals(null, uriRef8.fragment)

        val uriRef9 = URIReference.parse("http://a/b/c/d;p?q").resolve("#s")
        assertEquals("http://a/b/c/d;p?q#s", uriRef9.toString())
        assertEquals(false, uriRef9!!.isRelativeReference)
        assertEquals("http", uriRef9.scheme)
        assertEquals(true, uriRef9.hasAuthority())
        assertEquals("a", uriRef9.authority.toString())
        assertEquals(null, uriRef9.userinfo)
        assertEquals("a", uriRef9.host.toString())
        assertEquals("a", uriRef9.host!!.value)
        assertEquals(HostType.REGNAME, uriRef9.host!!.type)
        assertEquals(-1, uriRef9.port)
        assertEquals("/b/c/d;p", uriRef9.path)
        assertEquals("q", uriRef9.query)
        assertEquals("s", uriRef9.fragment)

        val uriRef10 = URIReference.parse("http://a/b/c/d;p?q").resolve("g#s")
        assertEquals("http://a/b/c/g#s", uriRef10.toString())
        assertEquals(false, uriRef10!!.isRelativeReference)
        assertEquals("http", uriRef10.scheme)
        assertEquals(true, uriRef10.hasAuthority())
        assertEquals("a", uriRef10.authority.toString())
        assertEquals(null, uriRef10.userinfo)
        assertEquals("a", uriRef10.host.toString())
        assertEquals("a", uriRef10.host!!.value)
        assertEquals(HostType.REGNAME, uriRef10.host!!.type)
        assertEquals(-1, uriRef10.port)
        assertEquals("/b/c/g", uriRef10.path)
        assertEquals(null, uriRef10.query)
        assertEquals("s", uriRef10.fragment)

        val uriRef11 = URIReference.parse("http://a/b/c/d;p?q").resolve("g?y#s")
        assertEquals("http://a/b/c/g?y#s", uriRef11.toString())
        assertEquals(false, uriRef11!!.isRelativeReference)
        assertEquals("http", uriRef11.scheme)
        assertEquals(true, uriRef11.hasAuthority())
        assertEquals("a", uriRef11.authority.toString())
        assertEquals(null, uriRef11.userinfo)
        assertEquals("a", uriRef11.host.toString())
        assertEquals("a", uriRef11.host!!.value)
        assertEquals(HostType.REGNAME, uriRef11.host!!.type)
        assertEquals(-1, uriRef11.port)
        assertEquals("/b/c/g", uriRef11.path)
        assertEquals("y", uriRef11.query)
        assertEquals("s", uriRef11.fragment)

        val uriRef12 = URIReference.parse("http://a/b/c/d;p?q").resolve(";x")
        assertEquals("http://a/b/c/;x", uriRef12.toString())
        assertEquals(false, uriRef12!!.isRelativeReference)
        assertEquals("http", uriRef12.scheme)
        assertEquals(true, uriRef12.hasAuthority())
        assertEquals("a", uriRef12.authority.toString())
        assertEquals(null, uriRef12.userinfo)
        assertEquals("a", uriRef12.host.toString())
        assertEquals("a", uriRef12.host!!.value)
        assertEquals(HostType.REGNAME, uriRef12.host!!.type)
        assertEquals(-1, uriRef12.port)
        assertEquals("/b/c/;x", uriRef12.path)
        assertEquals(null, uriRef12.query)
        assertEquals(null, uriRef12.fragment)

        val uriRef13 = URIReference.parse("http://a/b/c/d;p?q").resolve("g;x")
        assertEquals("http://a/b/c/g;x", uriRef13.toString())
        assertEquals(false, uriRef13!!.isRelativeReference)
        assertEquals("http", uriRef13.scheme)
        assertEquals(true, uriRef13.hasAuthority())
        assertEquals("a", uriRef13.authority.toString())
        assertEquals(null, uriRef13.userinfo)
        assertEquals("a", uriRef13.host.toString())
        assertEquals("a", uriRef13.host!!.value)
        assertEquals(HostType.REGNAME, uriRef13.host!!.type)
        assertEquals(-1, uriRef13.port)
        assertEquals("/b/c/g;x", uriRef13.path)
        assertEquals(null, uriRef13.query)
        assertEquals(null, uriRef13.fragment)

        val uriRef14 = URIReference.parse("http://a/b/c/d;p?q").resolve("g;x?y#s")
        assertEquals("http://a/b/c/g;x?y#s", uriRef14.toString())
        assertEquals(false, uriRef14!!.isRelativeReference)
        assertEquals("http", uriRef14.scheme)
        assertEquals(true, uriRef14.hasAuthority())
        assertEquals("a", uriRef14.authority.toString())
        assertEquals(null, uriRef14.userinfo)
        assertEquals("a", uriRef14.host.toString())
        assertEquals("a", uriRef14.host!!.value)
        assertEquals(HostType.REGNAME, uriRef14.host!!.type)
        assertEquals(-1, uriRef14.port)
        assertEquals("/b/c/g;x", uriRef14.path)
        assertEquals("y", uriRef14.query)
        assertEquals("s", uriRef14.fragment)

        val uriRef15 = URIReference.parse("http://a/b/c/d;p?q").resolve("")
        assertEquals("http://a/b/c/d;p?q", uriRef15.toString())
        assertEquals(false, uriRef15!!.isRelativeReference)
        assertEquals("http", uriRef15.scheme)
        assertEquals(true, uriRef15.hasAuthority())
        assertEquals("a", uriRef15.authority.toString())
        assertEquals(null, uriRef15.userinfo)
        assertEquals("a", uriRef15.host.toString())
        assertEquals("a", uriRef15.host!!.value)
        assertEquals(HostType.REGNAME, uriRef15.host!!.type)
        assertEquals(-1, uriRef15.port)
        assertEquals("/b/c/d;p", uriRef15.path)
        assertEquals("q", uriRef15.query)
        assertEquals(null, uriRef15.fragment)

        val uriRef16 = URIReference.parse("http://a/b/c/d;p?q").resolve(".")
        assertEquals("http://a/b/c/", uriRef16.toString())
        assertEquals(false, uriRef16!!.isRelativeReference)
        assertEquals("http", uriRef16.scheme)
        assertEquals(true, uriRef16.hasAuthority())
        assertEquals("a", uriRef16.authority.toString())
        assertEquals(null, uriRef16.userinfo)
        assertEquals("a", uriRef16.host.toString())
        assertEquals("a", uriRef16.host!!.value)
        assertEquals(HostType.REGNAME, uriRef16.host!!.type)
        assertEquals(-1, uriRef16.port)
        assertEquals("/b/c/", uriRef16.path)
        assertEquals(null, uriRef16.query)
        assertEquals(null, uriRef16.fragment)

        val uriRef17 = URIReference.parse("http://a/b/c/d;p?q").resolve("./")
        assertEquals("http://a/b/c/", uriRef17.toString())
        assertEquals(false, uriRef17!!.isRelativeReference)
        assertEquals("http", uriRef17.scheme)
        assertEquals(true, uriRef17.hasAuthority())
        assertEquals("a", uriRef17.authority.toString())
        assertEquals(null, uriRef17.userinfo)
        assertEquals("a", uriRef17.host.toString())
        assertEquals("a", uriRef17.host!!.value)
        assertEquals(HostType.REGNAME, uriRef17.host!!.type)
        assertEquals(-1, uriRef17.port)
        assertEquals("/b/c/", uriRef17.path)
        assertEquals(null, uriRef17.query)
        assertEquals(null, uriRef17.fragment)

        val uriRef18 = URIReference.parse("http://a/b/c/d;p?q").resolve("..")
        assertEquals("http://a/b/", uriRef18.toString())
        assertEquals(false, uriRef18!!.isRelativeReference)
        assertEquals("http", uriRef18.scheme)
        assertEquals(true, uriRef18.hasAuthority())
        assertEquals("a", uriRef18.authority.toString())
        assertEquals(null, uriRef18.userinfo)
        assertEquals("a", uriRef18.host.toString())
        assertEquals("a", uriRef18.host!!.value)
        assertEquals(HostType.REGNAME, uriRef18.host!!.type)
        assertEquals(-1, uriRef18.port)
        assertEquals("/b/", uriRef18.path)
        assertEquals(null, uriRef18.query)
        assertEquals(null, uriRef18.fragment)

        val uriRef19 = URIReference.parse("http://a/b/c/d;p?q").resolve("../")
        assertEquals("http://a/b/", uriRef19.toString())
        assertEquals(false, uriRef19!!.isRelativeReference)
        assertEquals("http", uriRef19.scheme)
        assertEquals(true, uriRef19.hasAuthority())
        assertEquals("a", uriRef19.authority.toString())
        assertEquals(null, uriRef19.userinfo)
        assertEquals("a", uriRef19.host.toString())
        assertEquals("a", uriRef19.host!!.value)
        assertEquals(HostType.REGNAME, uriRef19.host!!.type)
        assertEquals(-1, uriRef19.port)
        assertEquals("/b/", uriRef19.path)
        assertEquals(null, uriRef19.query)
        assertEquals(null, uriRef19.fragment)

        val uriRef20 = URIReference.parse("http://a/b/c/d;p?q").resolve("../g")
        assertEquals("http://a/b/g", uriRef20.toString())
        assertEquals(false, uriRef20!!.isRelativeReference)
        assertEquals("http", uriRef20.scheme)
        assertEquals(true, uriRef20.hasAuthority())
        assertEquals("a", uriRef20.authority.toString())
        assertEquals(null, uriRef20.userinfo)
        assertEquals("a", uriRef20.host.toString())
        assertEquals("a", uriRef20.host!!.value)
        assertEquals(HostType.REGNAME, uriRef20.host!!.type)
        assertEquals(-1, uriRef20.port)
        assertEquals("/b/g", uriRef20.path)
        assertEquals(null, uriRef20.query)
        assertEquals(null, uriRef20.fragment)

        val uriRef21 = URIReference.parse("http://a/b/c/d;p?q").resolve("../..")
        assertEquals("http://a/", uriRef21.toString())
        assertEquals(false, uriRef21!!.isRelativeReference)
        assertEquals("http", uriRef21.scheme)
        assertEquals(true, uriRef21.hasAuthority())
        assertEquals("a", uriRef21.authority.toString())
        assertEquals(null, uriRef21.userinfo)
        assertEquals("a", uriRef21.host.toString())
        assertEquals("a", uriRef21.host!!.value)
        assertEquals(HostType.REGNAME, uriRef21.host!!.type)
        assertEquals(-1, uriRef21.port)
        assertEquals("/", uriRef21.path)
        assertEquals(null, uriRef21.query)
        assertEquals(null, uriRef21.fragment)

        val uriRef22 = URIReference.parse("http://a/b/c/d;p?q").resolve("../../")
        assertEquals("http://a/", uriRef22.toString())
        assertEquals(false, uriRef22!!.isRelativeReference)
        assertEquals("http", uriRef22.scheme)
        assertEquals(true, uriRef22.hasAuthority())
        assertEquals("a", uriRef22.authority.toString())
        assertEquals(null, uriRef22.userinfo)
        assertEquals("a", uriRef22.host.toString())
        assertEquals("a", uriRef22.host!!.value)
        assertEquals(HostType.REGNAME, uriRef22.host!!.type)
        assertEquals(-1, uriRef22.port)
        assertEquals("/", uriRef22.path)
        assertEquals(null, uriRef22.query)
        assertEquals(null, uriRef22.fragment)

        val uriRef23 = URIReference.parse("http://a/b/c/d;p?q").resolve("../../g")
        assertEquals("http://a/g", uriRef23.toString())
        assertEquals(false, uriRef23!!.isRelativeReference)
        assertEquals("http", uriRef23.scheme)
        assertEquals(true, uriRef23.hasAuthority())
        assertEquals("a", uriRef23.authority.toString())
        assertEquals(null, uriRef23.userinfo)
        assertEquals("a", uriRef23.host.toString())
        assertEquals("a", uriRef23.host!!.value)
        assertEquals(HostType.REGNAME, uriRef23.host!!.type)
        assertEquals(-1, uriRef23.port)
        assertEquals("/g", uriRef23.path)
        assertEquals(null, uriRef23.query)
        assertEquals(null, uriRef23.fragment)

        val uriRef24 = URIReference.parse("http://a/b/c/d;p?q").resolve("g?y/./x")
        assertEquals("http://a/b/c/g?y/./x", uriRef24.toString())
        assertEquals(false, uriRef24!!.isRelativeReference)
        assertEquals("http", uriRef24.scheme)
        assertEquals(true, uriRef24.hasAuthority())
        assertEquals("a", uriRef24.authority.toString())
        assertEquals(null, uriRef24.userinfo)
        assertEquals("a", uriRef24.host.toString())
        assertEquals("a", uriRef24.host!!.value)
        assertEquals(HostType.REGNAME, uriRef24.host!!.type)
        assertEquals(-1, uriRef24.port)
        assertEquals("/b/c/g", uriRef24.path)
        assertEquals("y/./x", uriRef24.query)
        assertEquals(null, uriRef24.fragment)

        val uriRef25 = URIReference.parse("http://a/b/c/d;p?q").resolve("g?y/../x")
        assertEquals("http://a/b/c/g?y/../x", uriRef25.toString())
        assertEquals(false, uriRef25!!.isRelativeReference)
        assertEquals("http", uriRef25.scheme)
        assertEquals(true, uriRef25.hasAuthority())
        assertEquals("a", uriRef25.authority.toString())
        assertEquals(null, uriRef25.userinfo)
        assertEquals("a", uriRef25.host.toString())
        assertEquals("a", uriRef25.host!!.value)
        assertEquals(HostType.REGNAME, uriRef25.host!!.type)
        assertEquals(-1, uriRef25.port)
        assertEquals("/b/c/g", uriRef25.path)
        assertEquals("y/../x", uriRef25.query)
        assertEquals(null, uriRef25.fragment)

        val uriRef26 = URIReference.parse("http://a/b/c/d;p?q").resolve("g#s/./x")
        assertEquals("http://a/b/c/g#s/./x", uriRef26.toString())
        assertEquals(false, uriRef26!!.isRelativeReference)
        assertEquals("http", uriRef26.scheme)
        assertEquals(true, uriRef26.hasAuthority())
        assertEquals("a", uriRef26.authority.toString())
        assertEquals(null, uriRef26.userinfo)
        assertEquals("a", uriRef26.host.toString())
        assertEquals("a", uriRef26.host!!.value)
        assertEquals(HostType.REGNAME, uriRef26.host!!.type)
        assertEquals(-1, uriRef26.port)
        assertEquals("/b/c/g", uriRef26.path)
        assertEquals(null, uriRef26.query)
        assertEquals("s/./x", uriRef26.fragment)

        val uriRef27 = URIReference.parse("http://a/b/c/d;p?q").resolve("g#s/../x")
        assertEquals("http://a/b/c/g#s/../x", uriRef27.toString())
        assertEquals(false, uriRef27!!.isRelativeReference)
        assertEquals("http", uriRef27.scheme)
        assertEquals(true, uriRef27.hasAuthority())
        assertEquals("a", uriRef27.authority.toString())
        assertEquals(null, uriRef27.userinfo)
        assertEquals("a", uriRef27.host.toString())
        assertEquals("a", uriRef27.host!!.value)
        assertEquals(HostType.REGNAME, uriRef27.host!!.type)
        assertEquals(-1, uriRef27.port)
        assertEquals("/b/c/g", uriRef27.path)
        assertEquals(null, uriRef27.query)
        assertEquals("s/../x", uriRef27.fragment)

        TestUtils.assertThrowsNPE<Throwable>(
            "The input string must not be null.",
            { URIReference.parse("http://a/b/c/d;p?q").resolve(null) })

        TestUtils.assertThrowsISE<Throwable>(
            "The base URI must have a scheme.",
            { URIReference.parse("/a/b/c/d;p?q").resolve("g") })

        TestUtils.assertThrowsISE<Throwable>(
            "The base URI must not have a fragment.",
            { URIReference.parse("http://a/b/c/d;p?q#s").resolve("g") })
    }


    @Test
    fun test_normalize() {
        val uriRef1 = URIReference.parse("hTTp://example.com/").normalize()
        assertEquals("http://example.com/", uriRef1.toString())
        assertEquals(false, uriRef1!!.isRelativeReference)
        assertEquals("http", uriRef1.scheme)
        assertEquals(true, uriRef1.hasAuthority())
        assertEquals("example.com", uriRef1.authority.toString())
        assertEquals(null, uriRef1.userinfo)
        assertEquals("example.com", uriRef1.host.toString())
        assertEquals("example.com", uriRef1.host!!.value)
        assertEquals(HostType.REGNAME, uriRef1.host!!.type)
        assertEquals(-1, uriRef1.port)
        assertEquals("/", uriRef1.path)
        assertEquals(null, uriRef1.query)
        assertEquals(null, uriRef1.fragment)

        val uriRef2 = URIReference.parse("http://example.com/").normalize()
        assertEquals(true, uriRef2!!.hasAuthority())
        assertEquals("example.com", uriRef2.authority.toString())
        assertEquals(null, uriRef2.userinfo)
        assertEquals("example.com", uriRef2.host.toString())
        assertEquals("example.com", uriRef2.host!!.value)
        assertEquals(HostType.REGNAME, uriRef2.host!!.type)
        assertEquals(-1, uriRef2.port)
        assertEquals(null, uriRef2.query)
        assertEquals(null, uriRef2.fragment)

        val uriRef3 = URIReference.parse("http://%75ser@example.com/").normalize()
        assertEquals("http://user@example.com/", uriRef3.toString())
        assertEquals(false, uriRef3!!.isRelativeReference)
        assertEquals("http", uriRef3.scheme)
        assertEquals(true, uriRef3.hasAuthority())
        assertEquals("user@example.com", uriRef3.authority.toString())
        assertEquals("user", uriRef3.userinfo)
        assertEquals("example.com", uriRef3.host.toString())
        assertEquals("example.com", uriRef3.host!!.value)
        assertEquals(HostType.REGNAME, uriRef3.host!!.type)
        assertEquals(-1, uriRef3.port)
        assertEquals("/", uriRef3.path)
        assertEquals(null, uriRef3.query)
        assertEquals(null, uriRef3.fragment)

        val uriRef4 = URIReference.parse("http://%e3%83%a6%e3%83%bc%e3%82%b6%e3%83%bc@example.com/").normalize()
        assertEquals("http://%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC@example.com/", uriRef4.toString())
        assertEquals(false, uriRef4!!.isRelativeReference)
        assertEquals("http", uriRef4.scheme)
        assertEquals(true, uriRef4.hasAuthority())
        assertEquals("%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC@example.com", uriRef4.authority.toString())
        assertEquals("%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC", uriRef4.userinfo)
        assertEquals("example.com", uriRef4.host.toString())
        assertEquals("example.com", uriRef4.host!!.value)
        assertEquals(HostType.REGNAME, uriRef4.host!!.type)
        assertEquals(-1, uriRef4.port)
        assertEquals("/", uriRef4.path)
        assertEquals(null, uriRef4.query)
        assertEquals(null, uriRef4.fragment)

        val uriRef5 = URIReference.parse("http://%65%78%61%6D%70%6C%65.com/").normalize()
        assertEquals("http://example.com/", uriRef5.toString())
        assertEquals(false, uriRef5!!.isRelativeReference)
        assertEquals("http", uriRef5.scheme)
        assertEquals(true, uriRef5.hasAuthority())
        assertEquals("example.com", uriRef5.authority.toString())
        assertEquals(null, uriRef5.userinfo)
        assertEquals("example.com", uriRef5.host.toString())
        assertEquals("example.com", uriRef5.host!!.value)
        assertEquals(HostType.REGNAME, uriRef5.host!!.type)
        assertEquals(-1, uriRef5.port)
        assertEquals("/", uriRef5.path)
        assertEquals(null, uriRef5.query)
        assertEquals(null, uriRef5.fragment)

        val uriRef6 = URIReference.parse("http://%e4%be%8b.com/").normalize()
        assertEquals("http://%E4%BE%8B.com/", uriRef6.toString())
        assertEquals(false, uriRef6!!.isRelativeReference)
        assertEquals("http", uriRef6.scheme)
        assertEquals(true, uriRef6.hasAuthority())
        assertEquals("%E4%BE%8B.com", uriRef6.authority.toString())
        assertEquals(null, uriRef6.userinfo)
        assertEquals("%E4%BE%8B.com", uriRef6.host.toString())
        assertEquals("%E4%BE%8B.com", uriRef6.host!!.value)
        assertEquals(HostType.REGNAME, uriRef6.host!!.type)
        assertEquals(-1, uriRef6.port)
        assertEquals("/", uriRef6.path)
        assertEquals(null, uriRef6.query)
        assertEquals(null, uriRef6.fragment)

        val uriRef7 = URIReference.parse("http://LOCALhost/").normalize()
        assertEquals("http://localhost/", uriRef7.toString())
        assertEquals(false, uriRef7!!.isRelativeReference)
        assertEquals("http", uriRef7.scheme)
        assertEquals(true, uriRef7.hasAuthority())
        assertEquals("localhost", uriRef7.authority.toString())
        assertEquals(null, uriRef7.userinfo)
        assertEquals("localhost", uriRef7.host.toString())
        assertEquals("localhost", uriRef7.host!!.value)
        assertEquals(HostType.REGNAME, uriRef7.host!!.type)
        assertEquals(-1, uriRef7.port)
        assertEquals("/", uriRef7.path)
        assertEquals(null, uriRef7.query)
        assertEquals(null, uriRef7.fragment)

        val uriRef8 = URIReference.parse("http://example.com").normalize()
        assertEquals("http://example.com/", uriRef8.toString())
        assertEquals(false, uriRef8!!.isRelativeReference)
        assertEquals("http", uriRef8.scheme)
        assertEquals(true, uriRef8.hasAuthority())
        assertEquals("example.com", uriRef8.authority.toString())
        assertEquals(null, uriRef8.userinfo)
        assertEquals("example.com", uriRef8.host.toString())
        assertEquals("example.com", uriRef8.host!!.value)
        assertEquals(HostType.REGNAME, uriRef8.host!!.type)
        assertEquals(-1, uriRef8.port)
        assertEquals("/", uriRef8.path)
        assertEquals(null, uriRef8.query)
        assertEquals(null, uriRef8.fragment)

        val uriRef9 = URIReference.parse("http://example.com/%61/%62/%63/").normalize()
        assertEquals("http://example.com/a/b/c/", uriRef9.toString())
        assertEquals(false, uriRef9!!.isRelativeReference)
        assertEquals("http", uriRef9.scheme)
        assertEquals(true, uriRef9.hasAuthority())
        assertEquals("example.com", uriRef9.authority.toString())
        assertEquals(null, uriRef9.userinfo)
        assertEquals("example.com", uriRef9.host.toString())
        assertEquals("example.com", uriRef9.host!!.value)
        assertEquals(HostType.REGNAME, uriRef9.host!!.type)
        assertEquals(-1, uriRef9.port)
        assertEquals("/a/b/c/", uriRef9.path)
        assertEquals(null, uriRef9.query)
        assertEquals(null, uriRef9.fragment)

        val uriRef10 = URIReference.parse("http://example.com/%e3%83%91%e3%82%b9/").normalize()
        assertEquals("http://example.com/%E3%83%91%E3%82%B9/", uriRef10.toString())
        assertEquals(false, uriRef10!!.isRelativeReference)
        assertEquals("http", uriRef10.scheme)
        assertEquals(true, uriRef10.hasAuthority())
        assertEquals("example.com", uriRef10.authority.toString())
        assertEquals(null, uriRef10.userinfo)
        assertEquals("example.com", uriRef10.host.toString())
        assertEquals("example.com", uriRef10.host!!.value)
        assertEquals(HostType.REGNAME, uriRef10.host!!.type)
        assertEquals(-1, uriRef10.port)
        assertEquals("/%E3%83%91%E3%82%B9/", uriRef10.path)
        assertEquals(null, uriRef10.query)
        assertEquals(null, uriRef10.fragment)

        val uriRef11 = URIReference.parse("http://example.com/a/b/c/../d/").normalize()
        assertEquals("http://example.com/a/b/d/", uriRef11.toString())
        assertEquals(false, uriRef11!!.isRelativeReference)
        assertEquals("http", uriRef11.scheme)
        assertEquals(true, uriRef11.hasAuthority())
        assertEquals("example.com", uriRef11.authority.toString())
        assertEquals(null, uriRef11.userinfo)
        assertEquals("example.com", uriRef11.host.toString())
        assertEquals("example.com", uriRef11.host!!.value)
        assertEquals(HostType.REGNAME, uriRef11.host!!.type)
        assertEquals(-1, uriRef11.port)
        assertEquals("/a/b/d/", uriRef11.path)
        assertEquals(null, uriRef11.query)
        assertEquals(null, uriRef11.fragment)

        val uriRef12 = URIReference.parse("http://example.com:80/").normalize()
        assertEquals("http://example.com/", uriRef12.toString())
        assertEquals(false, uriRef12!!.isRelativeReference)
        assertEquals("http", uriRef12.scheme)
        assertEquals(true, uriRef12.hasAuthority())
        assertEquals("example.com", uriRef12.authority.toString())
        assertEquals(null, uriRef12.userinfo)
        assertEquals("example.com", uriRef12.host.toString())
        assertEquals("example.com", uriRef12.host!!.value)
        assertEquals(HostType.REGNAME, uriRef12.host!!.type)
        assertEquals(-1, uriRef12.port)
        assertEquals("/", uriRef12.path)
        assertEquals(null, uriRef12.query)
        assertEquals(null, uriRef12.fragment)

        TestUtils.assertThrowsISE<Throwable>(
            "A relative references must be resolved before it can be normalized.",
            { URIReference.parse("//example.com").normalize() })
    }


    @Test
    fun test_compareTo() {
        assertEquals(
            0,
            URIReference.parse("http://example.com/a/b/c/").compareTo(URIReference.parse("http://example.com/a/b/c/"))
        )

        assertTrue(
            URIReference.parse("127.0.0.1").compareTo(URIReference.parse("http://example.com/a/b/c/")) < 0
        )

        TestUtils.assertThrowsNPE<Throwable>(
            "A null value is not comparable.",
            { URIReference.parse("http://example.com/a/b/c/").compareTo(null) })
    }
}
