/*
 * Copyright (C) 2024-2025 Hideki Ikeda
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.czeal.urireference

import org.czeal.urireference.TestUtils.assertThrowsISE
import org.czeal.urireference.TestUtils.assertThrowsNPE
import org.czeal.urireference.URIReference.Companion.parse
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import java.nio.charset.StandardCharsets


class URIReferenceResolverTest {
    @Test
    fun test_resolve() {
        val uriRef1 = URIReferenceResolver().resolve(
            parse("g:h", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("g:h", uriRef1.toString())
        Assertions.assertEquals(false, uriRef1!!.isRelativeReference)
        Assertions.assertEquals("g", uriRef1.scheme)
        Assertions.assertEquals(false, uriRef1.hasAuthority())
        Assertions.assertEquals(null, uriRef1.authority)
        Assertions.assertEquals(null, uriRef1.userinfo)
        Assertions.assertEquals(null, uriRef1.host)
        Assertions.assertEquals(-1, uriRef1.port)
        Assertions.assertEquals("h", uriRef1.path)
        Assertions.assertEquals(null, uriRef1.query)
        Assertions.assertEquals(null, uriRef1.fragment)

        val uriRef2 = URIReferenceResolver().resolve(
            parse("g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g", uriRef2.toString())
        Assertions.assertEquals(false, uriRef2!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef2.scheme)
        Assertions.assertEquals(true, uriRef2.hasAuthority())
        Assertions.assertEquals("a", uriRef2.authority.toString())
        Assertions.assertEquals(null, uriRef2.userinfo)
        Assertions.assertEquals("a", uriRef2.host.toString())
        Assertions.assertEquals("a", uriRef2.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef2.host!!.type)
        Assertions.assertEquals(-1, uriRef2.port)
        Assertions.assertEquals("/b/c/g", uriRef2.path)
        Assertions.assertEquals(null, uriRef2.query)
        Assertions.assertEquals(null, uriRef2.fragment)

        val uriRef3 = URIReferenceResolver().resolve(
            parse("./g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g", uriRef3.toString())
        Assertions.assertEquals(false, uriRef3!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef3.scheme)
        Assertions.assertEquals(true, uriRef3.hasAuthority())
        Assertions.assertEquals("a", uriRef3.authority.toString())
        Assertions.assertEquals(null, uriRef3.userinfo)
        Assertions.assertEquals("a", uriRef3.host.toString())
        Assertions.assertEquals("a", uriRef3.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef3.host!!.type)
        Assertions.assertEquals(-1, uriRef3.port)
        Assertions.assertEquals("/b/c/g", uriRef3.path)
        Assertions.assertEquals(null, uriRef3.query)
        Assertions.assertEquals(null, uriRef3.fragment)

        val uriRef4 = URIReferenceResolver().resolve(
            parse("g/", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g/", uriRef4.toString())
        Assertions.assertEquals(false, uriRef4!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef4.scheme)
        Assertions.assertEquals(true, uriRef4.hasAuthority())
        Assertions.assertEquals("a", uriRef4.authority.toString())
        Assertions.assertEquals(null, uriRef4.userinfo)
        Assertions.assertEquals("a", uriRef4.host.toString())
        Assertions.assertEquals("a", uriRef4.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef4.host!!.type)
        Assertions.assertEquals(-1, uriRef4.port)
        Assertions.assertEquals("/b/c/g/", uriRef4.path)
        Assertions.assertEquals(null, uriRef4.query)
        Assertions.assertEquals(null, uriRef4.fragment)

        val uriRef5 = URIReferenceResolver().resolve(
            parse("/g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/g", uriRef5.toString())
        Assertions.assertEquals(false, uriRef5!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef5.scheme)
        Assertions.assertEquals(true, uriRef4.hasAuthority())
        Assertions.assertEquals("a", uriRef4.authority.toString())
        Assertions.assertEquals(null, uriRef4.userinfo)
        Assertions.assertEquals("a", uriRef4.host.toString())
        Assertions.assertEquals("a", uriRef4.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef4.host!!.type)
        Assertions.assertEquals(-1, uriRef4.port)
        Assertions.assertEquals("/g", uriRef5.path)
        Assertions.assertEquals(null, uriRef5.query)
        Assertions.assertEquals(null, uriRef5.fragment)

        val uriRef6 = URIReferenceResolver().resolve(
            parse("//g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://g", uriRef6.toString())
        Assertions.assertEquals(false, uriRef6!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef6.scheme)
        Assertions.assertEquals(true, uriRef6.hasAuthority())
        Assertions.assertEquals("g", uriRef6.authority.toString())
        Assertions.assertEquals(null, uriRef6.userinfo)
        Assertions.assertEquals("g", uriRef6.host.toString())
        Assertions.assertEquals("g", uriRef6.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef6.host!!.type)
        Assertions.assertEquals(-1, uriRef6.port)
        Assertions.assertEquals("", uriRef6.path)
        Assertions.assertEquals(null, uriRef6.query)
        Assertions.assertEquals(null, uriRef6.fragment)

        val uriRef7 = URIReferenceResolver().resolve(
            parse("?y", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/d;p?y", uriRef7.toString())
        Assertions.assertEquals(false, uriRef7!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef7.scheme)
        Assertions.assertEquals(true, uriRef7.hasAuthority())
        Assertions.assertEquals("a", uriRef7.authority.toString())
        Assertions.assertEquals(null, uriRef7.userinfo)
        Assertions.assertEquals("a", uriRef7.host.toString())
        Assertions.assertEquals("a", uriRef7.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef7.host!!.type)
        Assertions.assertEquals(-1, uriRef7.port)
        Assertions.assertEquals("/b/c/d;p", uriRef7.path)
        Assertions.assertEquals("y", uriRef7.query)
        Assertions.assertEquals(null, uriRef7.fragment)

        val uriRef8 = URIReferenceResolver().resolve(
            parse("g?y", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g?y", uriRef8.toString())
        Assertions.assertEquals(false, uriRef8!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef8.scheme)
        Assertions.assertEquals(true, uriRef8.hasAuthority())
        Assertions.assertEquals("a", uriRef8.authority.toString())
        Assertions.assertEquals(null, uriRef8.userinfo)
        Assertions.assertEquals("a", uriRef8.host.toString())
        Assertions.assertEquals("a", uriRef8.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef8.host!!.type)
        Assertions.assertEquals(-1, uriRef8.port)
        Assertions.assertEquals("/b/c/g", uriRef8.path)
        Assertions.assertEquals("y", uriRef8.query)
        Assertions.assertEquals(null, uriRef8.fragment)

        val uriRef9 = URIReferenceResolver().resolve(
            parse("#s", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/d;p?q#s", uriRef9.toString())
        Assertions.assertEquals(false, uriRef9!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef9.scheme)
        Assertions.assertEquals(true, uriRef9.hasAuthority())
        Assertions.assertEquals("a", uriRef9.authority.toString())
        Assertions.assertEquals(null, uriRef9.userinfo)
        Assertions.assertEquals("a", uriRef9.host.toString())
        Assertions.assertEquals("a", uriRef9.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef9.host!!.type)
        Assertions.assertEquals(-1, uriRef9.port)
        Assertions.assertEquals("/b/c/d;p", uriRef9.path)
        Assertions.assertEquals("q", uriRef9.query)
        Assertions.assertEquals("s", uriRef9.fragment)

        val uriRef10 = URIReferenceResolver().resolve(
            parse("g#s", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g#s", uriRef10.toString())
        Assertions.assertEquals(false, uriRef10!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef10.scheme)
        Assertions.assertEquals(true, uriRef10.hasAuthority())
        Assertions.assertEquals("a", uriRef10.authority.toString())
        Assertions.assertEquals(null, uriRef10.userinfo)
        Assertions.assertEquals("a", uriRef10.host.toString())
        Assertions.assertEquals("a", uriRef10.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef10.host!!.type)
        Assertions.assertEquals(-1, uriRef10.port)
        Assertions.assertEquals("/b/c/g", uriRef10.path)
        Assertions.assertEquals(null, uriRef10.query)
        Assertions.assertEquals("s", uriRef10.fragment)

        val uriRef11 = URIReferenceResolver().resolve(
            parse("g?y#s", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g?y#s", uriRef11.toString())
        Assertions.assertEquals(false, uriRef11!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef11.scheme)
        Assertions.assertEquals(true, uriRef11.hasAuthority())
        Assertions.assertEquals("a", uriRef11.authority.toString())
        Assertions.assertEquals(null, uriRef11.userinfo)
        Assertions.assertEquals("a", uriRef11.host.toString())
        Assertions.assertEquals("a", uriRef11.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef11.host!!.type)
        Assertions.assertEquals(-1, uriRef11.port)
        Assertions.assertEquals("/b/c/g", uriRef11.path)
        Assertions.assertEquals("y", uriRef11.query)
        Assertions.assertEquals("s", uriRef11.fragment)

        val uriRef12 = URIReferenceResolver().resolve(
            parse(";x", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/;x", uriRef12.toString())
        Assertions.assertEquals(false, uriRef12!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef12.scheme)
        Assertions.assertEquals(true, uriRef12.hasAuthority())
        Assertions.assertEquals("a", uriRef12.authority.toString())
        Assertions.assertEquals(null, uriRef12.userinfo)
        Assertions.assertEquals("a", uriRef12.host.toString())
        Assertions.assertEquals("a", uriRef12.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef12.host!!.type)
        Assertions.assertEquals(-1, uriRef12.port)
        Assertions.assertEquals("/b/c/;x", uriRef12.path)
        Assertions.assertEquals(null, uriRef12.query)
        Assertions.assertEquals(null, uriRef12.fragment)

        val uriRef13 = URIReferenceResolver().resolve(
            parse("g;x", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g;x", uriRef13.toString())
        Assertions.assertEquals(false, uriRef13!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef13.scheme)
        Assertions.assertEquals(true, uriRef13.hasAuthority())
        Assertions.assertEquals("a", uriRef13.authority.toString())
        Assertions.assertEquals(null, uriRef13.userinfo)
        Assertions.assertEquals("a", uriRef13.host.toString())
        Assertions.assertEquals("a", uriRef13.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef13.host!!.type)
        Assertions.assertEquals(-1, uriRef13.port)
        Assertions.assertEquals("/b/c/g;x", uriRef13.path)
        Assertions.assertEquals(null, uriRef13.query)
        Assertions.assertEquals(null, uriRef13.fragment)

        val uriRef14 = URIReferenceResolver().resolve(
            parse("g;x?y#s", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g;x?y#s", uriRef14.toString())
        Assertions.assertEquals(false, uriRef14!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef14.scheme)
        Assertions.assertEquals(true, uriRef14.hasAuthority())
        Assertions.assertEquals("a", uriRef14.authority.toString())
        Assertions.assertEquals(null, uriRef14.userinfo)
        Assertions.assertEquals("a", uriRef14.host.toString())
        Assertions.assertEquals("a", uriRef14.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef14.host!!.type)
        Assertions.assertEquals(-1, uriRef14.port)
        Assertions.assertEquals("/b/c/g;x", uriRef14.path)
        Assertions.assertEquals("y", uriRef14.query)
        Assertions.assertEquals("s", uriRef14.fragment)

        val uriRef15 = URIReferenceResolver().resolve(
            parse("", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/d;p?q", uriRef15.toString())
        Assertions.assertEquals(false, uriRef15!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef15.scheme)
        Assertions.assertEquals(true, uriRef15.hasAuthority())
        Assertions.assertEquals("a", uriRef15.authority.toString())
        Assertions.assertEquals(null, uriRef15.userinfo)
        Assertions.assertEquals("a", uriRef15.host.toString())
        Assertions.assertEquals("a", uriRef15.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef15.host!!.type)
        Assertions.assertEquals(-1, uriRef15.port)
        Assertions.assertEquals("/b/c/d;p", uriRef15.path)
        Assertions.assertEquals("q", uriRef15.query)
        Assertions.assertEquals(null, uriRef15.fragment)

        val uriRef16 = URIReferenceResolver().resolve(
            parse(".", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/", uriRef16.toString())
        Assertions.assertEquals(false, uriRef16!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef16.scheme)
        Assertions.assertEquals(true, uriRef16.hasAuthority())
        Assertions.assertEquals("a", uriRef16.authority.toString())
        Assertions.assertEquals(null, uriRef16.userinfo)
        Assertions.assertEquals("a", uriRef16.host.toString())
        Assertions.assertEquals("a", uriRef16.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef16.host!!.type)
        Assertions.assertEquals(-1, uriRef16.port)
        Assertions.assertEquals("/b/c/", uriRef16.path)
        Assertions.assertEquals(null, uriRef16.query)
        Assertions.assertEquals(null, uriRef16.fragment)

        val uriRef17 = URIReferenceResolver().resolve(
            parse("./", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/", uriRef17.toString())
        Assertions.assertEquals(false, uriRef17!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef17.scheme)
        Assertions.assertEquals(true, uriRef17.hasAuthority())
        Assertions.assertEquals("a", uriRef17.authority.toString())
        Assertions.assertEquals(null, uriRef17.userinfo)
        Assertions.assertEquals("a", uriRef17.host.toString())
        Assertions.assertEquals("a", uriRef17.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef17.host!!.type)
        Assertions.assertEquals(-1, uriRef17.port)
        Assertions.assertEquals("/b/c/", uriRef17.path)
        Assertions.assertEquals(null, uriRef17.query)
        Assertions.assertEquals(null, uriRef17.fragment)

        val uriRef18 = URIReferenceResolver().resolve(
            parse("..", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/", uriRef18.toString())
        Assertions.assertEquals(false, uriRef18!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef18.scheme)
        Assertions.assertEquals(true, uriRef18.hasAuthority())
        Assertions.assertEquals("a", uriRef18.authority.toString())
        Assertions.assertEquals(null, uriRef18.userinfo)
        Assertions.assertEquals("a", uriRef18.host.toString())
        Assertions.assertEquals("a", uriRef18.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef18.host!!.type)
        Assertions.assertEquals(-1, uriRef18.port)
        Assertions.assertEquals("/b/", uriRef18.path)
        Assertions.assertEquals(null, uriRef18.query)
        Assertions.assertEquals(null, uriRef18.fragment)

        val uriRef19 = URIReferenceResolver().resolve(
            parse("../", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/", uriRef19.toString())
        Assertions.assertEquals(false, uriRef19!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef19.scheme)
        Assertions.assertEquals(true, uriRef19.hasAuthority())
        Assertions.assertEquals("a", uriRef19.authority.toString())
        Assertions.assertEquals(null, uriRef19.userinfo)
        Assertions.assertEquals("a", uriRef19.host.toString())
        Assertions.assertEquals("a", uriRef19.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef19.host!!.type)
        Assertions.assertEquals(-1, uriRef19.port)
        Assertions.assertEquals("/b/", uriRef19.path)
        Assertions.assertEquals(null, uriRef19.query)
        Assertions.assertEquals(null, uriRef19.fragment)

        val uriRef20 = URIReferenceResolver().resolve(
            parse("../g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/g", uriRef20.toString())
        Assertions.assertEquals(false, uriRef20.isRelativeReference)
        Assertions.assertEquals("http", uriRef20.scheme)
        Assertions.assertEquals(true, uriRef20.hasAuthority())
        Assertions.assertEquals("a", uriRef20.authority.toString())
        Assertions.assertEquals(null, uriRef20.userinfo)
        Assertions.assertEquals("a", uriRef20.host.toString())
        Assertions.assertEquals("a", uriRef20.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef20.host!!.type)
        Assertions.assertEquals(-1, uriRef20.port)
        Assertions.assertEquals("/b/g", uriRef20.path)
        Assertions.assertEquals(null, uriRef20.query)
        Assertions.assertEquals(null, uriRef20.fragment)

        val uriRef21 = URIReferenceResolver().resolve(
            parse("../..", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/", uriRef21.toString())
        Assertions.assertEquals(false, uriRef21!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef21.scheme)
        Assertions.assertEquals(true, uriRef21.hasAuthority())
        Assertions.assertEquals("a", uriRef21.authority.toString())
        Assertions.assertEquals(null, uriRef21.userinfo)
        Assertions.assertEquals("a", uriRef21.host.toString())
        Assertions.assertEquals("a", uriRef21.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef21.host!!.type)
        Assertions.assertEquals(-1, uriRef21.port)
        Assertions.assertEquals("/", uriRef21.path)
        Assertions.assertEquals(null, uriRef21.query)
        Assertions.assertEquals(null, uriRef21.fragment)

        val uriRef22 = URIReferenceResolver().resolve(
            parse("../../", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/", uriRef22.toString())
        Assertions.assertEquals(false, uriRef22!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef22.scheme)
        Assertions.assertEquals(true, uriRef22.hasAuthority())
        Assertions.assertEquals("a", uriRef22.authority.toString())
        Assertions.assertEquals(null, uriRef22.userinfo)
        Assertions.assertEquals("a", uriRef22.host.toString())
        Assertions.assertEquals("a", uriRef22.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef22.host!!.type)
        Assertions.assertEquals(-1, uriRef22.port)
        Assertions.assertEquals("/", uriRef22.path)
        Assertions.assertEquals(null, uriRef22.query)
        Assertions.assertEquals(null, uriRef22.fragment)

        val uriRef23 = URIReferenceResolver().resolve(
            parse("../../g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/g", uriRef23.toString())
        Assertions.assertEquals(false, uriRef23!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef23.scheme)
        Assertions.assertEquals(true, uriRef23.hasAuthority())
        Assertions.assertEquals("a", uriRef23.authority.toString())
        Assertions.assertEquals(null, uriRef23.userinfo)
        Assertions.assertEquals("a", uriRef23.host.toString())
        Assertions.assertEquals("a", uriRef23.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef23.host!!.type)
        Assertions.assertEquals(-1, uriRef23.port)
        Assertions.assertEquals("/g", uriRef23.path)
        Assertions.assertEquals(null, uriRef23.query)
        Assertions.assertEquals(null, uriRef23.fragment)

        val uriRef24 = URIReferenceResolver().resolve(
            parse("g?y/./x", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g?y/./x", uriRef24.toString())
        Assertions.assertEquals(false, uriRef24!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef24.scheme)
        Assertions.assertEquals(true, uriRef24.hasAuthority())
        Assertions.assertEquals("a", uriRef24.authority.toString())
        Assertions.assertEquals(null, uriRef24.userinfo)
        Assertions.assertEquals("a", uriRef24.host.toString())
        Assertions.assertEquals("a", uriRef24.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef24.host!!.type)
        Assertions.assertEquals(-1, uriRef24.port)
        Assertions.assertEquals("/b/c/g", uriRef24.path)
        Assertions.assertEquals("y/./x", uriRef24.query)
        Assertions.assertEquals(null, uriRef24.fragment)

        val uriRef25 = URIReferenceResolver().resolve(
            parse("g?y/../x", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g?y/../x", uriRef25.toString())
        Assertions.assertEquals(false, uriRef25!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef25.scheme)
        Assertions.assertEquals(true, uriRef25.hasAuthority())
        Assertions.assertEquals("a", uriRef25.authority.toString())
        Assertions.assertEquals(null, uriRef25.userinfo)
        Assertions.assertEquals("a", uriRef25.host.toString())
        Assertions.assertEquals("a", uriRef25.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef25.host!!.type)
        Assertions.assertEquals(-1, uriRef25.port)
        Assertions.assertEquals("/b/c/g", uriRef25.path)
        Assertions.assertEquals("y/../x", uriRef25.query)
        Assertions.assertEquals(null, uriRef25.fragment)

        val uriRef26 = URIReferenceResolver().resolve(
            parse("g#s/./x", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g#s/./x", uriRef26.toString())
        Assertions.assertEquals(false, uriRef26!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef26.scheme)
        Assertions.assertEquals(true, uriRef26.hasAuthority())
        Assertions.assertEquals("a", uriRef26.authority.toString())
        Assertions.assertEquals(null, uriRef26.userinfo)
        Assertions.assertEquals("a", uriRef26.host.toString())
        Assertions.assertEquals("a", uriRef26.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef26.host!!.type)
        Assertions.assertEquals(-1, uriRef26.port)
        Assertions.assertEquals("/b/c/g", uriRef26.path)
        Assertions.assertEquals(null, uriRef26.query)
        Assertions.assertEquals("s/./x", uriRef26.fragment)

        val uriRef27 = URIReferenceResolver().resolve(
            parse("g#s/../x", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
        )
        Assertions.assertEquals("http://a/b/c/g#s/../x", uriRef27.toString())
        Assertions.assertEquals(false, uriRef27!!.isRelativeReference)
        Assertions.assertEquals("http", uriRef27.scheme)
        Assertions.assertEquals(true, uriRef27.hasAuthority())
        Assertions.assertEquals("a", uriRef27.authority.toString())
        Assertions.assertEquals(null, uriRef27.userinfo)
        Assertions.assertEquals("a", uriRef27.host.toString())
        Assertions.assertEquals("a", uriRef27.host!!.value)
        Assertions.assertEquals(HostType.REGNAME, uriRef27.host!!.type)
        Assertions.assertEquals(-1, uriRef27.port)
        Assertions.assertEquals("/b/c/g", uriRef27.path)
        Assertions.assertEquals(null, uriRef27.query)
        Assertions.assertEquals("s/../x", uriRef27.fragment)

        assertThrowsNPE<Throwable>(
            "The input string must not be null.",
            {
                URIReferenceResolver().resolve(
                    URIReference.parse(null as String?, StandardCharsets.UTF_8),
                    parse("http://a/b/c/d;p?q", StandardCharsets.UTF_8)
                )
            })

        assertThrowsISE<Throwable>(
            "The base URI must have a scheme.",
            {
                URIReferenceResolver().resolve(
                    parse("g", StandardCharsets.UTF_8), parse("/a/b/c/d;p?q", StandardCharsets.UTF_8)
                )
            })

        assertThrowsISE<Throwable>(
            "The base URI must not have a fragment.",
            {
                URIReferenceResolver().resolve(
                    parse("g", StandardCharsets.UTF_8), parse("http://a/b/c/d;p?q#s", StandardCharsets.UTF_8)
                )
            })
    }
}
